apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nasty-pig-nodejs 
  janus-idp.io/tekton: nasty-pig-nodejs
  backstage.io/kubernetes-id: nasty-pig-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nasty-pig-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  