apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nasty-pig-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nasty-pig-nodejs 
  name: nasty-pig-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nasty-pig-nodejs 
